### ISSUE TITLE
I need help about bge-m3 training

### ISSUE THREAD

**Issue by jhyeom1545** [FlagOpen/FlagEmbedding#701]
I'm having trouble with the bge-m3 train.

Accordingly, I would like to ask you a few questions.

1. m3 train code
I learn the bge-m3 model on the H100 (80GB) * 8 server.
Below is the learning script.
Is there a problem with the learning script I'm using?
The reason for asking is that there are times when the model after training does not seem to show any improvement.
**script**
```
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 nohup torchrun --nproc_per_node 8 > './logs/240415/train_m3_240415_batch_size_8_1.out' \
-m FlagEmbedding.BGE_M3.run \
--deepspeed '/workspace/train_embedding/m3/FlagEmbedding/deepspeed/ds_config.json' \
--knowledge_distillation False \
--output_dir './result/240415/' \
--model_name_or_path 'BAAI/bge-m3' \
--normlized True \
--temperature 0.02 \
--do_train  \
--train_data '/workspace/train_embedding/data/m3/v9_train/split' \
--cache_path './cache' \
--per_device_train_batch_size 2 \
--query_max_len 512 \
--passage_max_len 8192 \
--small_threshold 200 \
--drop_threshold 200 \
--fp16  \
--train_group_size 8 \
--learning_rate 5e-6 \
--num_train_epochs 5 \
--negatives_cross_device True \
--logging_steps 10 \
--warmup_ratio 0.1 \
--weight_decay 0.01 \
--overwrite_output_dir True \
--gradient_checkpointing \
--save_strategy 'steps' \
--save_steps 1000 \
--save_total_limit 15 \
--sentence_pooling_method cls \
--same_task_within_batch True \
--shuffle_ratio 0.002 \
--enable_sub_batch True \
--unified_finetuning True \
--use_self_distill True &
```

2. efficient batching
Learn the bge-m3 model on the H100 (80GB) * 8 server as above.
When I used the efficient batch, I couldn't proceed with the learning because of CUDA out of memory issue.
When I use train_group_size of data.py as 8,
You had to change the 0-500 length batch to 24 batches -> 10 batches to learn.
Isn't the batch that is applied in the data.py code of train_group_size in 8 a batch size that is possible for one node?

4. knowledge distillation
For pos and neg scores for knowledge distillation, which model scores should I use?
ex) Use the sense score of the bge-m3 model or use the BAAI/bge-reranker-v2-gema

Thank you for reading it.

**Comment by hanhainebula** [comment]
Hi, I have read your questions. Here are some of my personal opinions:

1. The training script looks fine. Could you provide more information about "after training does not seem to show any improvement"? Generally speaking, training data can have a significant impact on the effectiveness of the model. Perhaps you can consider the issue of data quality.
2. We provide the batch_size we used in [`get_file_batch_size()`](https://github.com/FlagOpen/FlagEmbedding/blob/master/FlagEmbedding/BGE_M3/data.py#L122). If you use `split_data_by_length.py` correctly, there should not be OOM error (considering the same GPU memory, 80GB). It is worth noting that we updated the `split_data_by_length.py` in this [commit](https://github.com/FlagOpen/FlagEmbedding/commit/8799821722b1dff17dab07d683a458cfed22119e#diff-50dfa7658fc392704ffa9ce3ba75a06172c3b945f51e4d083b1645af8a7388dc). You should check if the data has been correctly split.
3. In our experiment, we used the scores from the rerankers. Maybe you can choose the most suitable reranker for your datasets to generate the scores for knowledge distillation. The [latest rerankers](https://github.com/FlagOpen/FlagEmbedding/tree/master/FlagEmbedding/llm_reranker) may be helpful.

**Comment by staoxiao** [comment]
> when I generate score using reranker, am I have to use normalize=True or False? (I'm using normalize=True Option)

Hi, @jhyeom1545 , you need to use scores before normalizing, i.e., normalize=False.  The distribution of normalized scores is too smoothed to provide useful signals.

**Comment by jhyeom1545** [comment]
@staoxiao Thank you for your help.

**Comment by yflyzhang** [comment]
> --query_max_len 512 \\
> --passage_max_len 8192 \

Hi @jhyeom1545 , by setting `passage_max_len=8192`, did it throw out an **out of memory** error for you?

By the way, by seeting for example `query_max_len=4096`, `passage_max_len=8192` and `train_group_size=8`, do you have any experiences or suggestions to solve the out of memory issue? Thank you!

**Comment by jhyeom1545** [comment]
@yflyzhang Hi 
I experienced an OOM (Out of Memory) issue in the previous code version. I resolved it by modifying the part where batch size was dynamically set. After reinstalling the git package, the OOM no longer occurs, and training is progressing smoothly.
